name: 'Publish Neon Library'
description: 'Publish a Neon library and its prebuilds.'
inputs:
  working-directory:
    description: 'Working directory of the library (for extracting package metadata), relative to repo root.'
    required: false
    default: '.'
  tarball-directory:
    description: 'Directory in which to find (or place) the tarballs to be published, relative to repo root.'
    required: false
    default: 'dist'
  node-version:
    description: 'Node version to install.'
    required: false
    default: ''
  registry-url:
    description: 'npm registry URL.'
    required: false
    default: ''
  fetch-binaries:
    description: 'Filename or glob to fetch binary packages from GitHub releases.'
    required: false
    default: ''
  tag:
    description: 'Tag name to fetch from GitHub releases (default: infer from pushed tag).'
    required: false
    default: ''
  github-release:
    description: 'Publish tarball to GitHub releases.'
    required: false
    default: false
  filename:
    description: 'Filename or glob of local tarballs.'
    required: false
    default: ''
branding:
  icon: 'upload'
  color: 'orange'
runs:
  using: "composite"
  steps:
    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs['node-version'] }}
        registry-url: ${{ inputs['registry-url'] }}
        cache: npm
    - name: Get Tag Name
      if: ${{ inputs['fetch-binaries'] && !inputs.tag }}
      uses: olegtarasov/get-tag@v2.1.2
      id: tagName
    - name: Normalize Tarball Directory
      id: tarballs
      shell: bash
      run: |
        mkdir -p ${{ inputs['tarball-directory'] }}
        cd ${{ inputs['tarball-directory'] }}
        echo "Normalizing tarball directory..."
        echo "abspath=$(pwd)"
        echo "abspath=$(pwd)" >> $GITHUB_OUTPUT
    - name: Fetch Packages
      if: ${{ inputs['fetch-binaries'] }}
      uses: robinraju/release-downloader@v1.7
      with:
        tag: ${{ inputs.tag || steps.tagName.outputs.tag }}
        fileName: ${{ inputs['fetch-binaries'] }}
        out-file-path: ${{ inputs['tarball-directory'] }}
    - name: Get Package Metadata
      id: package
      shell: bash
      run: |
        echo "version=$(cat package.json | jq -r .version)" > $GITHUB_OUTPUT
        echo "name=$(cat package.json | jq -r .name)" >> $GITHUB_OUTPUT
      working-directory: ${{ inputs['working-directory'] }}
    - name: Publish Binary Packages
      shell: bash
      run: |
        pwd
        ls
        for p in ${{ steps.package.outputs.name }}-*-${{ steps.package.outputs.version }}.tgz; do
          npm publish --access public $p
        done
      working-directory: ${{ inputs['tarball-directory'] }}
    - name: Publish Main Package
      if: ${{ !inputs['github-release'] }}
      shell: bash
      run: npm publish
      working-directory: ${{ inputs['working-directory'] }}
    - name: Pack Main Package
      if: ${{ inputs['github-release'] }}
      shell: bash
      run: |
        npm pack --pack-destination=${{ steps.tarballs.outputs.abspath }}
      working-directory: ${{ inputs['working-directory'] }}
    - name: Release Main Package
      if: ${{ inputs['github-release'] }}
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ inputs['tarball-directory'] }}/${{ steps.package.outputs.name }}-${{ steps.package.outputs.version }}.tgz
    - name: Publish Main Package
      if: ${{ inputs['github-release'] }}
      shell: bash
      run: |
        npm publish ${{ steps.package.outputs.name }}-${{ steps.package.outputs.version }}.tgz
      working-directory: ${{ inputs['tarball-directory'] }}
